# Generated by Django 3.2.6 on 2021-09-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=35)),
                ('titulo', models.CharField(max_length=35)),
                ('video_id', models.CharField(max_length=35)),
            ],
        ),
    ]
