# Generated by Django 3.2.6 on 2021-09-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_create_model_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
