# Generated by Django 3.2.6 on 2021-09-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_alterado_tamanho_titulo_para_50'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='titulo',
            field=models.CharField(max_length=60),
        ),
    ]
