
name: CI

on:
  pull_request:
    branches: [main]


jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS}}
      DJANGO_SETTINGS_MODULE: djangopythonpro.settings
      # Set health checks to wait until postgres has started
    services:
      postgres:
        image: postgres:9.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testedb
        ports: ["5432:5432"]


    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip

          pip install -r requirements-dev.txt

      - name: Copy env run migrations
        run: |
          cp contrib/env-sample .env
          python manage.py migrate

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |

          pytest .
      - name: Coverage
        env:
          CODECOV_TOKEN: "df3c9988-8bde-4aab-b03e-004c841729ce"
        run: |
          codecov

